stages:
  - package
  - deploy
package_app:
  stage: package
  image: docker:git
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - yarn
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG
  only:
    - master
  tags:
    - docker
    - privileged
  cache:
    paths:
      - node_modules