apiVersion: k8s.sandstorm.de/v1alpha1
kind: Database
metadata:
  namespace: til-max
  name: db
spec:
  databaseServer: mariadb1
---
apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  namespace: til-max
  name: app
spec:
  description: 'today i learned von Max Puchstein'
​
  hostNames:
    til-max.cloud.sandstorm.de: []

  stagingCertificates: false
​
  node:
    - worker1

  image: docker-hub.sandstorm.de/v2/sandstorm-labs/til-von-max/manifests/latest
​
  port: 3000

  envFromConfigMaps: [db]
​
  envFromSecrets: [db]
​
  sso:
    enabled: true
